### ISSUE TITLE
Cannot run api

### ISSUE THREAD

**Issue by CebulMaciej** [Mixeway/MixewayOpenVASRestAPI#5]
─$ java -jar ./target/MixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar --server.port=84
43 --server.ssl.key-store=pki/localhost.p12 --server.ssl.key-store-password=qwer
ty --server.ssl.trust-store=/etc/pki/localhost.jks --server.ssl.trust-store-pass
word=qwerty --openvasmd.socket=/usr/local/var/run/openvasmd.sock --allowed.users
=localhost

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

2021-08-25 06:55:10.910  INFO 2206 --- [           main] pl.orange.bst.mixer.Mix
erApplication     : Starting MixerApplication v1.1.0-SNAPSHOT on kali with PID 2
206 (/home/kali/mixewayopenvasrestapi/target/MixewayOpenVasRestAPI-1.1.0-SNAPSHO
T.jar started by kali in /home/kali/mixewayopenvasrestapi)
2021-08-25 06:55:10.918  INFO 2206 --- [           main] pl.orange.bst.mixer.Mix
erApplication     : No active profile set, falling back to default profiles: def
ault
2021-08-25 06:55:14.049  INFO 2206 --- [           main] o.s.b.w.embedded.tomcat
.TomcatWebServer  : Tomcat initialized with port(s): 8443 (https)
2021-08-25 06:55:14.072  INFO 2206 --- [           main] o.apache.catalina.core.
StandardService   : Starting service [Tomcat]
2021-08-25 06:55:14.077  INFO 2206 --- [           main] org.apache.catalina.cor
e.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2021-08-25 06:55:14.205  INFO 2206 --- [           main] o.a.c.c.C.[Tomcat].[loc
alhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-08-25 06:55:14.208  INFO 2206 --- [           main] o.s.web.context.Context
Loader            : Root WebApplicationContext: initialization completed in 3146
 ms
2021-08-25 06:55:15.330  INFO 2206 --- [           main] o.s.s.web.DefaultSecuri
tyFilterChain     : Creating filter chain: any request, [org.springframework.sec
urity.web.context.request.async.WebAsyncManagerIntegrationFilter@3fa2213, org.sp
ringframework.security.web.context.SecurityContextPersistenceFilter@55342f40, or
g.springframework.security.web.header.HeaderWriterFilter@6bea52d4, org.springfra
mework.security.web.authentication.logout.LogoutFilter@5bd82fed, org.springframe
work.security.web.authentication.preauth.x509.X509AuthenticationFilter@488eb7f2,
 org.springframework.security.web.savedrequest.RequestCacheAwareFilter@72ea6193,
 org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFi
lter@b6b1987, org.springframework.security.web.authentication.AnonymousAuthentic
ationFilter@3e7634b9, org.springframework.security.web.session.SessionManagement
Filter@40f70521, org.springframework.security.web.access.ExceptionTranslationFil
ter@4351c8c3, org.springframework.security.web.access.intercept.FilterSecurityIn
terceptor@5a7005d]
2021-08-25 06:55:16.098  INFO 2206 --- [           main] o.s.s.concurrent.Thread
PoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'      
2021-08-25 06:55:16.902  WARN 2206 --- [           main] org.apache.tomcat.util.
net.SSLUtilBase   : The JSSE TLS 1.3 implementation does not support authenticat
ion after the initial handshake and is therefore incompatible with optional clie
nt authentication
2021-08-25 06:55:16.966  INFO 2206 --- [           main] o.apache.catalina.core.
StandardService   : Stopping service [Tomcat]
2021-08-25 06:55:17.033  INFO 2206 --- [           main] ConditionEvaluationRepo
rtLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your 
application with 'debug' enabled.
2021-08-25 06:55:17.043 ERROR 2206 --- [           main] o.s.boot.SpringApplicat
ion               : Application run failed

org.springframework.boot.web.server.WebServerException: Unable to start embedded
 Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(To
mcatWebServer.java:215) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]        
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.startWebServer(ServletWebServerApplicationContext.java:297) ~[spring-
boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-b
oot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:553) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.
3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.
2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:747) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:397) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:315) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1226) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1215) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at pl.orange.bst.mixer.MixerApplication.main(MixerApplication.java:39) ~
[classes!/:1.1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]  
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48) ~[MixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[M
ixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[M
ixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
 ~[MixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFa
iled
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:231) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPrevi
ouslyRemovedConnectors(TomcatWebServer.java:278) ~[spring-boot-2.2.4.RELEASE.jar
!/:2.2.4.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(To
mcatWebServer.java:197) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]        
        ... 18 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
1008) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) 
~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:227) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: /home/kali/mixewayopenvasrestapi/
pki/localhost.p12 (No such file or directory)
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(Abst
ractJsseEndpoint.java:99) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(Abstrac
tJsseEndpoint.java:71) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:217) ~[t
omcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractE
ndpoint.java:1141) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.ja
va:1227) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:586) ~
[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
1005) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 22 common frames omitted
Caused by: java.io.FileNotFoundException: /home/kali/mixewayopenvasrestapi/pki/l
ocalhost.p12 (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]      
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219) ~[na
:na]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) ~[
na:na]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112) ~[
na:na]
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURL
Connection.java:86) ~[na:na]
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(
FileURLConnection.java:184) ~[na:na]
        at org.apache.catalina.startup.CatalinaBaseConfigurationSource.getResour
ce(CatalinaBaseConfigurationSource.java:116) ~[tomcat-embed-core-9.0.30.jar!/:9.
0.30]
        at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:198)
 ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKey
store(SSLHostConfigCertificate.java:206) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30
]
        at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.jav
a:283) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.j
ava:247) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(Abst
ractJsseEndpoint.java:97) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 28 common frames omitted

2021-08-25 06:55:17.056  INFO 2206 --- [           main] o.s.s.concurrent.Thread
PoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

**Comment by siewer** [comment]
file to TLS certificate on p12 is not found:

`/home/kali/mixewayopenvasrestapi/pki/localhost.p12 (No such file or directory)`

while entering 
`--server.ssl.key-store=pki/localhost.p12` try to use absolute path here

**Comment by CebulMaciej** [comment]
i did it, but i have changed name at certificate.p12, because script generate this one. Result is below. @siewer , could you help me? What i shuld try now? :)

Error starting ApplicationContext. To display the conditions report re-run your 
application with 'debug' enabled.
2021-08-25 07:14:53.652 ERROR 2553 --- [           main] o.s.boot.SpringApplicat
ion               : Application run failed

org.springframework.boot.web.server.WebServerException: Unable to start embedded
 Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(To
mcatWebServer.java:215) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]        
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.startWebServer(ServletWebServerApplicationContext.java:297) ~[spring-
boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-b
oot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:553) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.
3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.
2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:747) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:397) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:315) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1226) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1215) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at pl.orange.bst.mixer.MixerApplication.main(MixerApplication.java:39) ~
[classes!/:1.1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]  
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48) ~[MixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[M
ixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[M
ixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
 ~[MixewayOpenVasRestAPI-1.1.0-SNAPSHOT.jar:1.1.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFa
iled
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:231) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPrevi
ouslyRemovedConnectors(TomcatWebServer.java:278) ~[spring-boot-2.2.4.RELEASE.jar
!/:2.2.4.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(To
mcatWebServer.java:197) ~[spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]        
        ... 18 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
1008) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) 
~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:227) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: jsse.alias_no_key_entry
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(Abst
ractJsseEndpoint.java:99) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(Abstrac
tJsseEndpoint.java:71) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:217) ~[t
omcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractE
ndpoint.java:1141) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.ja
va:1227) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:586) ~
[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
1005) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 22 common frames omitted
Caused by: java.io.IOException: jsse.alias_no_key_entry
        at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.jav
a:328) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.j
ava:247) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(Abst
ractJsseEndpoint.java:97) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
        ... 28 common frames omitted

2021-08-25 07:14:53.661  INFO 2553 --- [           main] o.s.s.concurrent.Thread
PoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

**Comment by siewer** [comment]
` jsse.alias_no_key_entry`

while exporting or generating pkcs12 file with certificate and key please provide an alias "mixer" or create any alias on Your own and rewrite it using `--server.ssl.key-alias`

my proposal is to generate pkcs12 using:

`openssl pkcs12 -export -in my-cert.crt -inkey my-priv-key.key -out localhost.p12 -name "mixer"`

focus on -name part 


PS. I will try to improve docs to make It more clear

**Comment by CebulMaciej** [comment]
Exacly. I have done what you had written but now i have problem with not existing /etc/pki/localhost.jks
What is your advice now? @siewer

**Comment by siewer** [comment]
You can use default JRE `cacerts`

pls find location of Your JRE cacerts (ref: https://stackoverflow.com/questions/11936685/how-to-obtain-the-location-of-cacerts-of-the-default-java-installation) 

and then add:

`--server.ssl.trust-store=<location to cacerts>`

**Comment by CebulMaciej** [comment]
i found something like that : /etc/ssl/certs/java/cacerts. i'm trying

@siewer your solution works. You are my hero ! :+1:
